default:
  image: webdevops/php:8.0

variables:
  COMPOSER_CACHE_DIR: /cache/composer
  COMPOSER_ALLOW_SUPERUSER: "1"
  COMPOSER_NO_INTERACTION: "1"
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_JOB_ID/$CI_PROJECT_PATH
  MAILHOG_HOST: mailhog
  MAILHOG_SMTP_PORT: "1025"
  MAILHOG_API_PORT: "8025"
  PHP_MEMORY_LIMIT: "-1"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - lint
  - sca
  - test

lint:php:
  stage: lint
  before_script:
    - composer install --no-progress
  script:
    - composer lint -- --dry-run
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - when: on_success

sca:php:
  stage: sca
  before_script:
    - composer install --no-progress
    - mkdir -p .build
  script:
    - composer sca -- --error-format gitlab > .build/phpstan.json
  artifacts:
    reports:
      codequality: .build/phpstan.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - when: on_success

test:
  image: webdevops/php:${PHP_VERSION}
  stage: test
  services:
    - name: mailhog/mailhog
      alias: mailhog
  before_script:
    - >
      if [ "$COVERAGE" == "1" ]; then
        pecl channel-update pecl.php.net
        pecl install pcov
        docker-php-ext-enable pcov
      fi
  script:
    - composer self-update --${COMPOSER_VERSION}
    - composer --version
    - php --version
    - composer require --dev "composer/composer:^${COMPOSER_VERSION}.0" --no-progress
    - >
      if [ $UPDATE_CHECK_REF ]; then
        composer require "eliashaeussler/composer-update-check:dev-master#$UPDATE_CHECK_REF"
      fi
    - >
      if [ "$COVERAGE" == "1" ]; then
        COMPOSER_PROCESS_TIMEOUT=1000 composer test:ci -- --testdox
      else
        composer test:run -- --testdox
      fi
  parallel:
    matrix:
      - PHP_VERSION: ["7.1", "7.2", "7.3", "7.4"]
        COMPOSER_VERSION: ["1", "2"]
      - PHP_VERSION: "8.0"
        COMPOSER_VERSION: "1"
      - PHP_VERSION: "8.0"
        COMPOSER_VERSION: "2"
        COVERAGE: "1"
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: .build/coverage/junit.xml
