stages:
  - build
  - test
  - coverage

build:
  stage: build
  script:
    - cat gitlab-ci/test.yaml > generated-config.yaml
    - cat gitlab-ci/test.php*.yaml >> generated-config.yaml
  artifacts:
    paths:
      - generated-config.yaml
  only:
    - branches

test:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yaml
        job: build
    strategy: depend

coverage:
  stage: coverage
  script:
    - 'curl -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID"'
