variables:
  COMPOSER_CACHE_DIR: "/cache/composer"
  COMPOSER_ALLOW_SUPERUSER: "1"
  COMPOSER_NO_INTERACTION: "1"

before_script:
  - composer self-update
  - composer global require hirak/prestissimo --no-progress

stages:
  - test

# Test template
.test: &test-template
  stage: test
  image: webdevops/php:${PHP_VERSION}
  before_script:
    - pecl install pcov
    - docker-php-ext-enable pcov
  script:
    - >
      if [[ $TEST_COMPATIBILITY ]]; then
        composer require --dev pcov/clobber
        vendor/bin/pcov clobber
      fi
    - composer install --no-progress
    - COMPOSER_PROCESS_TIMEOUT=1000 composer test:ci -- --testdox
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: .build/coverage/junit.xml
  only:
    - branches

# Test: PHP 7.1
test:php7.1:
  <<: *test-template
  variables:
    PHP_VERSION: "7.1"
    TEST_COMPATIBILITY: "1"

# Test: PHP 7.2
test:php7.2:
  <<: *test-template
  variables:
    PHP_VERSION: "7.2"

# Test: PHP 7.3
test:php7.3:
  <<: *test-template
  variables:
    PHP_VERSION: "7.3"

# Test: PHP 7.4
test:php7.4:
  <<: *test-template
  variables:
    PHP_VERSION: "7.4"
