test:update-check:
  image: webdevops/php:${PHP_VERSION}
  stage: test
  services:
    - name: mailhog/mailhog
      alias: mailhog
  variables:
    PHP_MEMORY_LIMIT: "-1"
    PHP_MAX_EXECUTION_TIME: "600"
  before_script:
    - composer global require --dev --no-progress --prefer-stable brianium/paratest:"*"
    - composer self-update --${COMPOSER_VERSION}
    - composer --version
    - php --version
  script:
    - mkdir -p .build/coverage
    - composer require --dev "composer/composer:^${COMPOSER_VERSION}.0" --no-progress
    - composer require "eliashaeussler/composer-update-check:${UPDATE_CHECK_REF}"
    - /root/.composer/vendor/bin/paratest --runner=WrapperRunner -c phpunit.xml
  parallel:
    matrix:
      - PHP_VERSION: ["7.1", "7.2", "7.3", "7.4", "8.0"]
        COMPOSER_VERSION: ["1", "2"]
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${PHP_VERSION}-${COMPOSER_VERSION}"
    paths:
      - vendor/
    policy: pull
  artifacts:
    reports:
      junit: .build/coverage/junit.xml
  rules:
    - if: '$UPDATE_CHECK_REF'
      when: on_success
