name: Documentation
on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docs/build/docker-compose.yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Render docs
      - name: Build container
        run: docker-compose build --pull
      - name: Render HTML
        run: docker-compose run --rm docs build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rendered-docs
          path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: rendered-docs
          path: site/

      # Upload
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: composer-update-reporter.elias-haeussler.de
