name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  # Job: Run unit tests
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, Composer ${{ matrix.composer-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog
        env:
          MH_SMTP_BIND_ADDR: 0.0.0.0:2025
          MH_API_BIND_ADDR: 0.0.0.0:9025
          MH_UI_BIND_ADDR: 0.0.0.0:9025
        ports:
          - 2025:2025
          - 9025:9025
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.1", "7.2", "7.3", "7.4", "8.0", "8.1"]
        composer-version: ["1", "2"]
        dependencies: ["highest", "lowest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Install dependencies
      - name: Simulate Composer version
        run: |
          composer config platform.composer-plugin-api "${{ matrix.composer-version }}.99"
          composer config platform.composer-runtime-api "${{ matrix.composer-version }}.99"
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with="composer/composer:^${{ matrix.composer-version }}"
      - name: Update Composer version
        run: composer self-update --${{ matrix.composer-version }}

      # Run tests
      - name: Build coverage directory
        run: mkdir -p .build/coverage
      - name: Run tests
        run: composer test:run

  # Job: Collect and report test coverage
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog
        env:
          MH_SMTP_BIND_ADDR: 0.0.0.0:2025
          MH_API_BIND_ADDR: 0.0.0.0:9025
          MH_UI_BIND_ADDR: 0.0.0.0:9025
        ports:
          - 2025:2025
          - 9025:9025
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: pcov

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Build coverage directory
        run: mkdir -p .build/coverage
      - name: Run tests with coverage
        run: composer test:coverage

      # Report coverage
      - name: Fix coverage path
        working-directory: .build/coverage
        run: sed -i 's#/home/runner/work/composer-update-reporter/composer-update-reporter#${{ github.workspace }}#g' clover.xml
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/.build/coverage/clover.xml:clover
      - name: codecov report
        uses: codecov/codecov-action@v3
        with:
          directory: .build/coverage
          fail_ci_if_error: true
          verbose: true
